### ISSUE TITLE
RDB セットアップ

### ISSUE THREAD

**Issue by shogo0x2e** [shogo0x2e/career-path-prj#1]
- [ ] Prisma セットアップ
- [ ] docker-compose でローカル環境用に PostgreSQL を定義

https://hub.docker.com/_/postgres
```yaml
# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

```
